export const refund = [
  "transaction_id",
  "merchant_display_name",
  "transaction_type_id",
  "transaction_type_name",
  "txn_status_name",
  "txn_step_name",
  "acquirer_name",
  "payment_mode_name",
  "amount",
  "acquirer_response_code",
  "acquirer_response_description",
  "transaction_response_code",
  "transaction_start_date_time",
  "txn_completion_date_time",
  "time_to_complete",
  "transaction_response_message",
  "is_aggregator",
  "is_reversal",
  "pine_pg_integration_mode_name",
  "convenience_fees_amt_in_paise",
  "convenience_fees_gst_amt_in_paise",
  "convenience_fees_additional_amt_in_paise",
  "category",
  "business_technical_decline"
]
;

export const support = [
  "Case Number",
  "Date/Time",
  "Created Time",
  "Category",
  "Subject",
  "Corporate Name",
  "Mode of Payment",
  "Resolution"
]

export const settlement = [
  "transaction_id",
  "merchant_display_name",
  "txn_status_name",
  "acquirer_name",
  "issuer_name",
  "payment_mode_id",
  "payment_mode_name",
  "card_type_association_name",
  "amount",
  "is_aggregator",
  "is_reversal",
  "transaction_start_date_time",
  "txn_refund_amt",
  "batch_id",
  "nodal_account_bank",
  "actual_txn_amount",
  "refund_amount",
  "bank_charge_amount",
  "mdr_charge",
  "mdr_tax",
  "platform_fee",
  "mard_amount",
  "additonal_taxes",
  "bank_commision",
  "bank_service_tax",
  "amount_to_be_deducted_in_addition_to_bank_charges",
  "is_not_on_sell_rate",
  "convenience_fees_amt_in_paise",
  "convenience_fees_additional_amt_in_paise",
  "settlement_amount",
  "sds",
  "sdscycle",
  "program_name",
  "axis_payout_created",
  "payout_status",
  "payout_nodal_acc"
]
